apiVersion: v1
kind: Service
metadata:
  name: flask-experiment
spec:
  type: LoadBalancer
  selector:
    app: flask-experiment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30812
