apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-experiment
  labels:
    app: ktor-experiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktor-experiment
  template:
    metadata:
      labels:
        app: ktor-experiment
    spec:
      containers:
        - name: ktor-experiment
          image: ktor-experiment:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "2"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: experiment
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ktor-experiment-secret
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ktor-experiment-secret
                  key: postgres-password
