apiVersion: v1
kind: Service
metadata:
  name: spring-boot-experiment
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-experiment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30808