apiVersion: v1
kind: Service
metadata:
  name: express-experiment
spec:
  type: LoadBalancer
  selector:
    app: express-experiment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30813
