apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'spring-boot-experiment'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['192.168.49.2:30808']
      - job_name: 'gin-experiment'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['192.168.49.2:30809']
      - job_name: 'ktor-experiment'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['192.168.49.2:30810']
      - job_name: 'dotnet-experiment'
        metrics_path: '/metrics'
        static_configs:
          - targets: [ '192.168.49.2:30811' ]
      - job_name: 'flask-experiment'
        metrics_path: '/metrics'
        static_configs:
          - targets: [ '192.168.49.2:30812' ]
      - job_name: 'express-experiment'
        metrics_path: '/metrics'
        static_configs:
          - targets: [ '192.168.49.2:30813' ]
